# Generated by Django 4.0.1 on 2022-02-05 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 13, 25, 40, 749417)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 13, 25, 40, 749417)),
        ),
    ]
