export const PAGE_LOAD_REQUEST = 'PAGE_LOAD_REQUEST';
export const PAGE_LOAD_SUCCESS = 'PAGE_LOAD_SUCCESS';
export const PAGE_LOAD_FAIL = 'PAGE_LOAD_FAIL'	;

export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST';
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL';

export const COURSE_DETAIL_EDIT_REQUEST = 'COURSE_DETAIL_EDIT_REQUEST';
export const COURSE_DETAIL_EDIT_SUCCESS = 'COURSE_DETAIL_EDIT_SUCCESS';
export const COURSE_DETAIL_EDIT_FAIL = 'COURSE_DETAIL_EDIT_FAIL';

export const ENROLLMENT_REQUEST = 'ENROLLMENT_REQUEST';
export const ENROLLMENT_SUCCESS = 'ENROLLMENT_SUCCESS';
export const ENROLLMENT_FAIL = 'ENROLLMENT_FAIL';

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS  = "USER_LOGIN_SUCCESS   "
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGIN_LOGOUT = "USER_LOGIN_LOGOUT"